#!/bin/bash

export LOC="$PWD/out/target/product/arthur"
export Geno="$PWD"

mkdir -p "$LOC"/temp

cd "$LOC"/temp
echo "extract update.zip"
unzip -o -qq  "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip

echo "Making arthur Compatible Update script"
cd "$LOC"
cd "$LOC"/temp/META-INF/com/google/android
rm -rf updater-script
cp "$Geno"/device/zte/arthur/tools/updater-script "$LOC"/temp/META-INF/com/google/android/updater-script
echo Zipping Package
cd "$LOC"/temp
rm -rf "$LOC"/temp/recovery
rm -rf "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip
zip -9yr "$LOC"/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$LOGNAME.zip * > /dev/null
cd "$LOC"

echo Cleanup...
rm -rf "$LOC"/temp
sh "$Geno"/vendor/cyanogen/tools/squisher
echo done
